Feature/install and config sequelize
oicrruf/insurance-api pull request #10
Opened 2022-04-05 05:15 UTC by MarkRiv

2022-04-05 05:50 UTC, oicrruf requested changes

2022-04-05 05:50 UTC, oicrruf commented on bin/www
>  var app = require("../app");
Podrías cambiar todas las variables `var` por `const` 😅, ya vienen así desde el generador. Pero aprovechemos a cambairlas de una vez.

2022-04-05 05:50 UTC, oicrruf commented on config/config.js
> +  dbPort:  process.env.DB_PORT,
Debes de ser consistente en la manera de escribir por ejemplo, has usado un espacio y doble espacio entre los dos puntos (:) y el `process.env.`
Te recomiendo configurar Prettier y usar siempre la combinación de teclas ALT+SHIFT+F, antes de guardar el archivo, más adelantes configuraremos tareas de formateo en el código.

2022-04-05 05:50 UTC, oicrruf commented on db/config.js
> +const { config } = require('./../config/config');
¿Por qué usas './../..'?
¿No te funciona directamente '../'? 

Me parece raro y en otros archivos no lo usas así

2022-04-05 05:50 UTC, oicrruf commented on docker-compose.yaml
> +    - POSTGRES_PASSWORD=123
También en los archivo `yaml` podes usar ${VARIABLE_DE_ENTORNO} para llamar a la variable y no "quemarla"
https://docs.docker.com/compose/environment-variables/

2022-04-07 01:32 UTC, ceroncmcr approved these changes

2022-04-07 01:36 UTC, MarkRiv reviewed
@oicrruf podes revisar los ajustes que me solicitaste para incluir mis cambios. Gracias

2022-04-07 03:08 UTC, oicrruf approved these changes

2022-04-07 03:09 UTC, merged