Feature/create userid endpoint
oicrruf/insurance-api pull request #14
Opened 2022-04-10 16:49 UTC by ceroncmcr

The requested changes were made for the issue
Close #5

2022-04-10 22:29 UTC, MarkRiv approved these changes

2022-04-12 14:12 UTC, oicrruf requested changes

2022-04-12 14:12 UTC, oicrruf commented on .env.example
>  NEW_ENV=
Esta línea se puede eliminar del archivo .env original y al sincronizar en el commit verifica si se actualiza

2022-04-12 14:12 UTC, oicrruf commented on docker-compose.yaml
>        - PGADMIN_DEFAULT_EMAIL=mrivas@mail.com
Coordinate with @MarkRiv to remove these data from this file

- [ ] PGADMIN_DEFAULT_EMAIL
- [ ] PGADMIN_DEFAULT_PASSWORD

2022-04-12 14:12 UTC, oicrruf commented on routes/user.router.js
> +          message: 'Usuario no encontrado',
This is the type of message we should put in the language JSON, the validation and JOI generated messages that are translated by the package

2022-04-12 14:12 UTC, oicrruf commented on schemas/errorMessage.json
> +  }
Add messages in English or Spanish for "User not found" and "Usuario no encontrado".

2022-04-14 01:08 UTC, oicrruf approved these changes

2022-04-14 01:08 UTC, merged