feature new route health
oicrruf/insurance-api pull request #7
Opened 2022-03-31 19:34 UTC by ceroncmcr

2022-03-31 20:43 UTC, oicrruf requested changes

2022-03-31 20:43 UTC, oicrruf commented on routes/index.js
> +function routerApi(app){
Sólo usemos funciones de tipo flecha si es posible "()=>{}", hay algunas ocasiones en las que no es posible. Pero esto sucede con paquetes antiguos y que no tienen soporta de ECMAScrript 6

2022-03-31 20:43 UTC, oicrruf commented on app.js
>  app.use(express.static(path.join(__dirname, 'public')));
Creo que esta línea no la vamos a usar, se me olvidó borrarla 😥

2022-03-31 20:43 UTC, oicrruf commented on app.js
> +  res.json({ app: "insurance-api"});
Carga esa información desde el package.json también

2022-03-31 20:43 UTC, oicrruf commented on routes/health.router.js
> +var config = require("../package.json");
Usemos variables `const` o `let` (creo que el generador las pone como `var`), pero si hay `var` cambiemoslas todas. Cambia el nombre de `config` a `appInfo`, creo que será mejor así

2022-03-31 20:43 UTC, oicrruf commented on routes/health.router.js
> +});
```
router.get('/',(req, res) => {
    const {name, version} = appInfo
    res.json({ name, version});
});
```
Usando destructuración el código va a quedar mas fácil de leer y mantener, ese es un ejemplo

2022-03-31 21:19 UTC, oicrruf requested changes

2022-03-31 21:19 UTC, oicrruf commented on routes/health.router.js
> +        version: version
Cuando el nombre de la KEY es el mismo de la variable que vas a poner, basta con poner la variable

2022-03-31 21:39 UTC, oicrruf approved these changes

2022-04-01 16:58 UTC, MarkRiv approved these changes

2022-04-01 17:05 UTC, merged