feature new test route health
oicrruf/insurance-api pull request #8
Opened 2022-04-01 17:43 UTC by ceroncmcr

2022-04-01 17:50 UTC, oicrruf requested changes

2022-04-01 17:50 UTC, oicrruf commented on test/health.test.js
> +    test('is ContentType json', async () => {
Cambia todo el texto del nombre del test a minúsculas

2022-04-01 17:50 UTC, oicrruf commented on test/health.test.js
> +    test('is response data it ok', async () => {
Creo que sería mejor el nombre de: "to have name and version properties"

2022-04-01 17:50 UTC, oicrruf commented on test/health.test.js
> +describe('test route /healt', () => {
Con el nombre de la ruta es suficiente "health", que además está mal escrito 😅

2022-04-01 19:32 UTC, oicrruf approved these changes

2022-04-03 02:45 UTC, MarkRiv approved these changes

2022-04-03 02:45 UTC, merged